### ISSUE TITLE
[FEATURE]  create home-brew tap for MacOS

### ISSUE THREAD

**Issue by prabirshrestha** [SuperCuber/dotter#139]
Create homebrew tap for MacOS. https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap

**Comment by acovaci** [comment]
I've created a tap before, so if anyone from the devs would be happy to help me understand what needs to be put where, I'd be happy to take this.

**Comment by SuperCuber** [comment]
> what needs to be put where

as someone who hasn't created a tap before, that's exactly what I don't know 🙃 

I've created https://github.com/SuperCuber/homebrew-dotter so that it's usable with `brew install supercuber/dotter` - feel free to open a PR there, and I'll be happy to help if you have questions about the building/releasing process

**Comment by prabirshrestha** [comment]
You need to create a `Formula/dotter.rb` file with contents similar to this.

https://github.com/mongodb/homebrew-brew/blob/master/Formula/mongodb-community.rb

**Comment by quintrino** [comment]
Hey, just curious, what's motivating having it be a tap, separate from Homebrew-core, rather than just a formula added directly to homebrew core? 

I'm not quite sure how ripgrep has done it, but it seems like they have the fomula for brew to install here
https://github.com/BurntSushi/ripgrep/blob/master/pkg/brew/ripgrep-bin.rb

Symlinked to a file called HomebrewFormula
https://github.com/BurntSushi/ripgrep/blob/master/HomebrewFormula

And then push those changes up to homebrew here
https://github.com/Homebrew/homebrew-core/blob/master/Formula/r/ripgrep.rb
via a PR. 

Whether you end up going tap or formula, I'm excited you're working on getting this brew compatible!

**Comment by SuperCuber** [comment]
@quintrino the "motivation" is that I have no idea how homebrew packaging works 🙃 
"working on" is also an overstatement, I'm waiting for someone with more knowledge and motivation than me to do what's needed :)

**Comment by zuisong** [comment]
https://github.com/Homebrew/homebrew-core/pull/157934

I have create a PR to `homebrew-core` repo. 😄

**Comment by prabirshrestha** [comment]
Seems like the PR is merged and I can verify it works via `brew install dotter`. Probably want to update the README.md.
