### ISSUE TITLE
[FEATURE] ARM binaries for Linux

### ISSUE THREAD

**Issue by orhun** [SuperCuber/dotter#150]
**Is your feature request related to a problem? Please describe.**

Someone on the AUR asked if it is possible to add ARM support for the `-bin` package: https://aur.archlinux.org/packages/dotter-rs-bin

It is theoretically possible but upstream needs to distribute ARM binaries for that. I realized there is already a `.arm` artifact on the release page but it is built for MacOS:

https://github.com/SuperCuber/dotter/blob/1071fbcbed0c74b90cf6c8db8bd9b0106037f7a9/.github/workflows/build-for-release.yml#L18-L21

**Describe the solution you'd like**

Distribute Linux ARM binaries via GitHub similar to the other artifacts. 

**Describe alternatives you've considered**
None.

**Additional context**
I would like to contribute this if you find it appropriate.

**Comment by SuperCuber** [comment]
Sounds like a great idea! Might want to rewrite the matrix strategy to be based on a "build name" instead of os like in the CI https://github.com/SuperCuber/dotter/blob/1071fbcbed0c74b90cf6c8db8bd9b0106037f7a9/.github/workflows/continuous-integration.yml#L14 (and if course best to add a check there for that target)
