### ISSUE TITLE
[FEATURE] Support binary files

### ISSUE THREAD

**Issue by nicmr** [SuperCuber/dotter#164]
**Is your feature request related to a problem? Please describe.**
I would like to use dotter to manage binary files that are part of my configuration.
However, when deploying these, I get the following error:
```
[ WARN] File "foo.binary" is not valid UTF-8 - detecting as symlink. Explicitly specify it to silence this message.
[ERROR] Creating symlink "foo.binary" -> "destination" but target isn't a symlink. Skipping.
```

**Describe the solution you'd like**
dotter supports binary files

**Describe alternatives you've considered**

**Additional context**
I'm willing to contribute this myself, I'm going to look at the code but might need some pointers.

**Comment by nicmr** [comment]
Consequently, if the initial check supports reliably determining a file is neither a utf-8 string nor a template, it could handle these independently and not interfere with the handling of the already supported file types. This functionality would not necessarily be limited to binary files, but to any non-utf8 non-symlink files.

**Comment by SuperCuber** [comment]
I think the problem is that the error message is not clear enough - the creasing for `skipping` in this case is that the destination file already exists and is something different than Dotter would create (presumably, this is a copy of your binary file)

To delete and overwrite the target file you need to supply the `-f` flag.
I'll change the message to `target already exists and isn't a symlink`
