### ISSUE TITLE
Conditional include based on OS

### ISSUE THREAD

**Issue by Firehawke** [SuperCuber/dotter#171]
### Environment
If applicable, provide the following details:
- **OS**: Windows 11 with Ubuntu and NixOS on WSL2
- **Dotter version**: 0.13.0

### The question
Since I have the same hostname on Windows and WSL, I'm trying to work out how to conditionally include the windows.toml only when running in Windows. This would be the first step in having it only install the Windows Terminal configuration files when run from Windows and ignore it when from any WSL2 distro. 

I've tried using the following in the hostname toml file, and it didn't work, as it doesn't seem to like templating at that level. Any suggestions?

```
{{#if (eq dotter.os windows)}}includes = [".dotter/windows.toml"]{{/if}}
packages = ["windowsterminalpreview"]
```

**Comment by Cornelius-Figgle** [comment]
can you not change the WSL hostname?

**Comment by Firehawke** [comment]
Only if I'm willing to sacrifice automatic /etc/hosts generation, which is not a particularly good idea.

**Comment by Cornelius-Figgle** [comment]
ah I see. I agree that it would be good if handlebars could be used everywhere.

**Comment by SuperCuber** [comment]
This is not very possible to do, at least not with the way things are implemented right now, since the Handlebars engine is only created once we have gathered and mostly finalized all the configuration (exception made for the `if` field on files)

The workaround I can think of right now is:
1. Move most of your configuration out of `local.toml` and into a shared `windows-machine.toml`
2. Define an alias or manually use the `-l / --local-config` option to select a separate local.toml for each platform.
3. In each of them, import the `windows-machine.toml` as well as `windows.toml` or `wsl.toml` respectively

---

I could see it being a feature to have 
```
includes = [{file = ".dotter/windows.toml, if = "(eq dotter.os windows)"}]
```
But that's very incompatible with how configuration is loaded currently (included files are imported and merged into one big context before Handlebars is initialized)
