### ISSUE TITLE
[FEATURE] Improve Path Finding

### ISSUE THREAD

**Issue by JP-Ellis** [SuperCuber/dotter#34]
**Is your feature request related to a problem? Please describe.**
Currently, dotter is not very smart about finding files.

For example, consider the following files:

```
~/.dotter/global.toml
~/.dotter/local.toml
~/.dotter/foo/config
```

And here are two use cases:

1. From the home directory
  - If no arguments are given, dotter will correctly find the tomnl files, but then fail to find the config files as it looks for them in `~/foo/config`.
  - If the location of the toml files is given, dotter still fails to find the config files.
2. From ~/.dotter`
  - If no arguments are given, dotter doesn't find the toml files as it looks for them in `~/.dotter/.dotter/global.toml`
  - If the toml files are given, everything works fine.

**Describe the solution you'd like**
Dotter should try and by smarter about finding the toml files and the other files.

For the toml files, it should probably be in this order:

- If CLI flag given:
  1. Use CLI flag
  2. Fail if not found
- If CLI flag omitted
  1. `$(pwd)/global.toml`
  2. `$(pwd)/.dotter/global.toml`
  2. `~/.dotter/global.toml`
  3. Fail if not found

and for the config files, they probably should only be relative to the global (or local) toml file?  So it would try it in this order:

1. `$TOML_DIR`
2. `$TOML_DIR/..`

Ultimately for more complicated configuration, the `$TOML_DIR` might vary on a per-file basis (as there can be multiple `toml` files), I think a sensible order of precendence would be:

1. `local.toml`
2. included toml
3. `global.toml`
4. current working directory if all else fails

If that is something you would consider, I can help implementing this and make a pull request when I get time.

**Comment by SuperCuber** [comment]
I don't think I understand your use case, do you have both your dotter configuration and the dotfiles in the same directory? Is there a reason not to use the default locations? Or maybe you're trying to have dotter manage the dotfiles in their target location directly?

In general, dotter is intended to be used from the repository root, while the repository has a `.dotter` directory at its root.

**Comment by JP-Ellis** [comment]
I saw in your wiki that you suggest using:

```
~
├── .dotfiles
│  ├── .dotter
│  │  ├── global.toml
│  │  └── local.toml
│  └── foo
│     └── config
```

but I don't really like having the `.dotter` hiddens subdirectory and I want to make it clearer that I'm using dotter.  Afterall, the entire directory has little purpose without dotter being there to manage the config files (I would have to manually symlink everything).  As a result I was hoping to have something like this:

```
~
├── .dotter
│  ├── foo
│  │  └── config
│  ├── global.toml
│  └── local.toml
```

But by default `dotter` doesn't do a great job of finding where things are.  I'll update the original post's logic for searching for config files.

**Comment by SuperCuber** [comment]
Right now dotter doesn't search at all - it just takes the relative path given and uses it. So, for example, if you execute from `~` it would find the configs since they are in the default relative location (`.dotter/global.toml`), and the source would need to be specified like `".dotter/foo/config" = "~/path/to/target"`. If you run that from `~` it should work.

---

Alternatively, you can effectively rename `.dotter` to something else by setting the flags for
* `local.toml`
* `global.toml`
* `cache.toml`
* cache folder

You can even use a shell alias that does that every time.

---

Do you think it's worth having a flag for `--config-directory` specifically? That would address your issue directly.

I'd need to think about how it would interact with the other flags mentioned above - maybe when it's present, all of the other configuration location flags are interpreted relative to it, but otherwise relative to current directory... Or I could have the default values be:

* `--config-directory` = `.dotter`
* `--local-config` = `local.toml`
* .. etc

And even if you in theory wanted to then scatter the configs in whatever way you want, you could set `--config-directory /` in the extreme case.

**Comment by JP-Ellis** [comment]
I don't think it's necessarily worth having a `--config-directory`, I think the simplest would be to have the config files referenced by the `toml` file being relative to that toml file.  This seems most sensible because I don't see many instances where you would separate the toml file from the other config files.  This would allow for example to have two separate configs which can be deployed/undeployed separately.

The only issue with what I mentioned is that there's some ambiguity as to which of the toml file is used, but having a clear precendence would remove the ambiguity.

**Comment by SuperCuber** [comment]
> I don't see many instances where you would separate the toml file from the other config files

One such instance are my [own dotfiles](https://github.com/supercuber/dotfiles). Both the `global.toml` and `local.toml` are intended to apply to the whole repository, with deploying/undeploying seperately supported by packages.

Seperating them by directory then having a config per directory is a fine idea - for example, GNU Stow uses a similar approach, but this is not the direction I chose to go in because it's less intuitive to me personally.

**Comment by JP-Ellis** [comment]
Would you consider a pull request which looks for files relative to the toml file?  I would be happy to have a go.

**Comment by SuperCuber** [comment]
I don't think so. I just don't see the advantage of having it - it just feels like hard-coding your use case into the program instead of using the command line flags to customize it.

I don't have a problem adding new flags in case you're missing some to make your use case work.

**Comment by SuperCuber** [comment]
Plus, implementing searching and relative file paths would add more complexity that would need to be explained and documented and would raise the barrier of entry to using the tool which I think is already quite high - to make full use, you need to understand in what order the toml files are evaluated and how they're merged together for example

**Comment by JP-Ellis** [comment]
Fair enough, I can understand avoiding unnecessary complexity.  Personally I think it is a shame that `dotter` can only be run from one directory and I would have liked having it be smarter about finding files in a way that is similar to how `cargo` works.

I might still implement this in a fork if I get time. but you don't need to pull that into the main repository.

**Comment by SuperCuber** [comment]
A couple versions ago dotter would try to climb a directory every time it failed to find a configuration. You can go through the releases and find that commit if you want something to base your code on. Also dotter used to have a `--directory` flag that would basically just change cwd before doing anything else, I think it was removed in the same commit.

**Comment by SuperCuber** [comment]
I thought a bit more about this, I feel like I don't really understand how you intend to use this.
For example, the way I use it is I clone my dotfiles repo and rename it to `~/.dotfiles`, then cd into it and run dotter from there, along with any git commands. In general, you're only supposed to re-run dotter after changing some files or after a `git pull`, and for that you want your cwd to be in the repo anyways... It makes little sense to me to run dotter from outside of the repository to be honest.

**Comment by SuperCuber** [comment]
Closing for now, feel free to reopen if you have something to add and definitely I'd like to know if you end up actually forking and adding something :)
