### ISSUE TITLE
Elevate privileges for system global files

### ISSUE THREAD

**Issue by LokiVKlokeNaAndoke** [SuperCuber/dotter#37]
**Is your feature request related to a problem? Please describe.**
Currently, when you have this in your config:
```
[pacman.files]
"etc/pacman.conf" = "/etc/pacman.conf"
```
dotter errors out with:
```
[ERROR] Failed to create symlink symlink "etc/pacman.conf" -> "/etc/pacman.conf"
Caused by:
    create target symlink
    create symlink
    Permission denied (os error 13)
```

**Describe the solution you'd like**
Probably what systemctl does when run as a regular user:
```
==== AUTHENTICATING FOR org.freedesktop.systemd1.manage-units ====
Authentication is required to restart 'some.service'.
Authenticating as: user
Password: 
```
In other words, dotter should integrate with polkit and request elevation when current permissions aren't enough.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by SuperCuber** [comment]
Why not run dotter with sudo?

I will look into this sometime over the next few days though - will add if it's easy

**Comment by LokiVKlokeNaAndoke** [comment]
I did run it with sudo, and all relative (with `~/`) symlinks ended up in the /root directory, which isn't useful, and also it's a security risk.

**Comment by SuperCuber** [comment]
I see. And now that I think of it, even if ~ was resolved to the correct directory it would still write files owned by root which wouldn't be editable by the user which is just annoying...

By the way - technically paths starting with ~ are absolute, because they are relative to the root, not the current directory :P

**Comment by LokiVKlokeNaAndoke** [comment]
Everything is relative, man 🌿
If being serious though, another solution could be specifying an owner for links and a user home location. This way even if run by root the links would have correct locations and permissions.

**Comment by SuperCuber** [comment]
Regarding home directory, you can maybe find a workaround in the meantime [here](https://unix.stackexchange.com/a/91572)

> another solution could be specifying an owner for links

I think this is a good point - maybe you want to write certain configuration files as certain users, maybe your nginx config is written as user `www` or something...
I also need to think about how this would be handled on windows - probably by just printing a warning.

---

For myself - looks like rust standard library doesn't have a method to change ownership of a file.
Gonna yoink [chown](https://github.com/uutils/coreutils/blob/master/src/uucore/src/lib/features/perms.rs#L103) from uutils.
Might also want to use [sudo](https://docs.rs/sudo/0.5.0/sudo/) crate.

---

So, plan of action as I see it right now:
- Add `owner` field to [complex targets](https://github.com/SuperCuber/dotter/wiki/Setup-and-Configuration#complex-target).
  Maybe this is a good time to allow this on directories - all files under the directory will inherit the `type` and `owner`.
- If there's an `owner` field set anywhere in the files, Dotter will ask for elevation when it starts up.
  This leaves an edge case for undeploying (technically deploying with no files), since deleting also requires elevation...
  Guess I can go for the alternative of just requesting elevation when I get `permission denied`.
  - [ ] Make sure to handle repeat `permission denied` - some stuff is denied permission even from root so it can technically happen
- Old user as well as `$HOME` variable will be saved before changing to root, and files without an `owner` field will be set to that user and `~` resolved to old home.
- `owner` field can be either int in which case it's interpreted as uid or string in which case it's interpreted as username
  - In case of username, it will need to be translated to a uid
  - [ ] What about gid? It needs to be set correctly too... Maybe..?
- Each file with an `owner` field will be first written as root then `chown`ed

What do you think, @LokiVKlokeNaAndoke ?

**Comment by LokiVKlokeNaAndoke** [comment]
Thanks for making such a detailed response!
I think your plan is great.

**Comment by LokiVKlokeNaAndoke** [comment]
I have thought about your notes again, and I have a few suggestions. 
You can do what [paru](https://github.com/Morganamilo/paru) does: invoke the relevant commands through the [Command](https://doc.rust-lang.org/std/process/struct.Command.html) API. Here's the [relevant line](https://github.com/Morganamilo/paru/blob/4533a39a628ccd8b302c7a9343ed58f22b5685f0/src/exec.rs#L80) from paru source code. 
It would be easier to implement because of using the existing infrastructure.

> If there's an owner field set anywhere in the files, Dotter will ask for elevation when it starts up.
This leaves an edge case for undeploying (technically deploying with no files), since deleting also requires elevation...
Guess I can go for the alternative of just requesting elevation when I get permission denied.

Instead asking for elevation on startup you could leverage the existing `sudo` and `chown` programs by launching them from your binary. You can check if your program has permissions to do stuff by simply doing stuff, and if it can't then try with sudo.

This would entail creating and linking files through `Command` API though, which isn't ideal (probably).

**Comment by SuperCuber** [comment]
I don't think using Command to perform my actions has an advantage over using regular functions, unless I'm missing something.

In fact, it's even a disadvantage, since to get the error I'd need to parse the stderr or something while using functions would get the same effect but with better error handling.

**Comment by SuperCuber** [comment]
Progress:
- [X] Implement `owner` field
- [X] Implement elevation when field `owner` exists
- [ ] Implement deployment - pay attention to edge cases, for example where only owner was added
- [ ] Implement elevation when permission denied during deletion
- [ ] Make sure `~` and `owner=None` work as desired
- [ ] Implement username -> uid conversion
- [ ] Think about `gid`

**Comment by SuperCuber** [comment]
>I don't think using Command to perform my actions has an advantage over using regular functions, unless I'm missing something.

@LokiVKlokeNaAndoke after partly implementing it, I'm starting to understand that this could be the better solution, because right now if I elevate at the beginning, then every file created will be owned by root, even ones that aren't supposed to be (like parent directories of files or cache files)

I guess I'll try using `sudo cat` with the file piped into it and `sudo chown`... See if it's any better.

**Comment by SuperCuber** [comment]
This is still kinda complicated but feels like it's gonna be simpler:

### Templates
```
render and write cache as current user, then:

nonexist -> no owner (creating)
    mkdir -p
    read cache as user, write target as user
    chmod --reference
nonexist -> with owner (creating)
    sudo -u owner mkdir -p
    read cache as user, write target with sudo
    sudo chmod --reference
exist no owner -> exist no owner (updating)
    read cache as user, write target as user
    fs::copy_permissions(cache, target)
exist owner -> exist no owner (updating)    |
exist owner -> exist same owner (updating)  |
exist owner -> exist other owner (updating)
    sudo chown owner
    read cache as user, write target with sudo
    sudo chmod --reference
exist no owner -> nonexist (deleting)
    rm
exist owner -> nonexist (deleting)
    sudo rm
```

### Symlinks
Hopefully just remove previous if needed (owner changed), then `sudo -u owner ln -s`

**Comment by SuperCuber** [comment]
New plan of action:
- [X] Implement `owner` field
- [ ] Implement getting current file's owner and seeing if it's the same as current user
- [ ] Transform perform_template_deployment() into perform_template_render()
- [ ] Implement all deployment cases
- [ ] Think about `gid`

**Comment by SuperCuber** [comment]
This is now implemented for templates in https://github.com/SuperCuber/dotter/commit/23232f528e06e08ddd9a5991687a6add8589c62b

- [ ] Implement for symlinks

**Comment by SuperCuber** [comment]
- [ ] Test test test

**Comment by SuperCuber** [comment]
This is now tested enough to close the issue, but I will do some additional testing before the next Release.
