### ISSUE TITLE
Command Injection Vulnerability in filesystem::parse_path

### ISSUE THREAD

**Issue by LunarLambda** [SuperCuber/dotter#4]
[filesystem::parse_path](https://github.com/SuperCuber/dotter/blob/master/src/filesystem.rs#L5) formats a shell command using an unsanitized string from `files.toml`, allowing arbitrary shell commands to be injected.

This is as simple as having a semicolon anywhere in your destination path:
```toml
"foo.txt" = ";xterm"
```

Running `dotter deploy` spawns an xterm window. (If you do not have xterm installed, change it to something else)

Consider using [`std::fs::canonicalize`](https://doc.rust-lang.org/stable/std/fs/fn.canonicalize.html) instead, or at the very least, sanitizing the input strings appropriately.

**Comment by SuperCuber** [comment]
Thanks for the issue!

It's not much of a risk from a security standpoint since if you're running dotter on untrusted configurations you're already giving an attacker the ability to overwrite any file you have write access to (so don't do it), but it is a concern from a portability standpoint, and opening an xterm window is another bad side effect.

Fixed in 9220310 .
