### ISSUE TITLE
[FEATURE] Built in dotfiles folder varable

### ISSUE THREAD

**Issue by SIMULATAN** [SuperCuber/dotter#97]
**Is your feature request related to a problem? Please describe.**
I want to modify the alias specified by the default `.zshrc` to modify the file in the dotfiles directory and not the target one.

**Describe the solution you'd like**
A built-in `dotter.dotfiles_folder` variable that has the **absolute** path to the root of the dotfiles folder

**Alternatives**
I tried to make my own pre-deploy hook with the code
```bash
{{assign "dotfiles_folder" (command_output "pwd")}}
```
but unfortunately it can't find the variable (the assignement worked, I can use it in the line below as seen in the screenshot)
![screenshot](https://user-images.githubusercontent.com/63104422/171599741-36fa2097-8edc-4438-88f8-810e76c8f393.png)
![code](https://user-images.githubusercontent.com/63104422/171599867-65a40f90-0f4e-4200-ae70-79c2f316096b.png)

Thank you for the great work, I absolutely love the tool and would be very happy to see updates :heart:

**Comment by SuperCuber** [comment]
Yep I don't think you can use assign for this because it works on a per-file basis in handlebars.

Should be easy enough to add, PRs welcome but I will get to it over the next couple of days otherwise

For reference the relevant code is here
https://github.com/SuperCuber/dotter/blob/98b747f2b6859bd9188fbb15f552530b1a28d3aa/src/handlebars_helpers.rs#L295
probably best to name it something like `root` so that it's available in `dotter.root`

**Comment by SIMULATAN** [comment]
Thanks!

I'll see what I can do, unfortunately I don't really have experience in rust but I'll see what I can do.

**Comment by SuperCuber** [comment]
Implemented in https://github.com/SuperCuber/dotter/commit/1582b58bea715e70506f247e4cf505ad09be0d0f , to be included in next release.
